title: Default Page
preset: page
fields:
  title_1:
    label: title_1
    type: textarea
    size: small
  wat:
    label: wat
    type: textarea
    size: large
  usp1:
    label: usp1
    type: textarea
    size: small
  usp2:
    label: usp2
    type: textarea
    size: small
  usp3:
    label: usp3
    type: textarea
    size: small
  usp4:
    label: usp4
    type: textarea
    size: small
  usp5:
    label: usp5
    type: textarea
    size: small
  title_2:
    label: title_2
    type: textarea
    size: small
  wanneer_1:
    label: wanneer_1
    type: textarea
    size: small
  wanneer_2:
    label: wanneer_2
    type: textarea
    size: small
  wanneer_3:
    label: wanneer_3
    type: textarea
    size: small
  wanneer_4:
    label: wanneer_4
    type: textarea
    size: small
  wanneer_5:
    label: wanneer_5
    type: textarea
    size: small
  wanneer_6:
    label: wanneer_6
    type: textarea
    size: small
  title_keuze:
    label: title_keuze
    type: textarea
    size: small
  title_wie:
    label: title_wie
    type: textarea
    size: small
  title_deelnemers:
    label: title_deelnemers
    type: textarea
    size: small
  deelnemers_introtekst:
    label: deelnemers_introtekst
    type: textarea
    size: medium
  facilitator:
    label: facilitator
    type: textarea
    size: small
  product_owner:
    label: product_owner
    type: textarea
    size: small
  visual_designer:
    label: visual_designer
    type: textarea
    size: small
  ux_designer:
    label: ux_designer
    type: textarea
    size: small
  developer:
    label: developer
    type: textarea
    size: small
  copy_writer:
    label: copy_writer
    type: textarea
    size: small
  maandag_description:
    label: maandag_description
    type: textarea
    size: small
  dinsdag_description:
    label: dinsdag_description
    type: textarea
    size: small
  woensdag_description:
    label: woensdag_description
    type: textarea
    size: small
  donderdag_description:
    label: donderdag_description
    type: textarea
    size: small
  vrijdag_description:
    label: vrijdag_description
    type: textarea
    size: small
  zaterdag_description:
    label: zaterdag_description
    type: textarea
    size: small
